services:
  postgres:
    container_name: postgres_revisao_etapa3
    image: postgres:17
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - revisao_etapa3:/var/lib/postgresql/data
    
volumes:
  revisao_etapa3: